[package]
name = "zktron"
type = "bin"
authors = ["Ultrasound Labs"]

[dependencies]
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
